#!/usr/bin/env ruby
require 'shellwords'

BUILTINS = {
  'cd' => lambda { |dir| Dir.chdir(dir) },
  'exit' => lambda { |code = 0| exit(code.to_i) },
  'exec' => lambda { |*command| exec *command }
}

loop do
  $stdout.print '(relp) -> '
  ln = $stdin.gets.strip
  command, *arguments = Shellwords.shellsplit(ln)

  if BUILTINS[command]
    BUILTINS[command].call(*arguments)
  else
    pid = fork {
      exec ln
    }

    Process.wait pid
  end
end
